Repository neiman-marcus/terraform-aws-jenkins-ha-agents, pull requests merged in 2020-07, with the labels that each got.

#48 Updated Jenkins version to 2.235.1
  README.md
  examples/full/main.tf
  examples/full/terraform.tfvars
  examples/full/variables.tf
  examples/minimum/main.tf
  variables.tf
Labels: awaiting response, version upgrade

#49 Update examples to work w/ registry. Update badges
  README.md
  examples/full/main.tf
  examples/minimum/main.tf
Labels: documentation

#52 Update main.tf
  main.tf
Labels: bug

#53 Update to jenkins 2.235.2.
  README.md
  examples/full/terraform.tfvars
  examples/full/variables.tf
  main.tf
  variables.tf
Labels: version upgrade

#54 Resolve merging quotes and agent volume var.
  main.tf
Labels: bug

#55 Include LB outputs.
  examples/full/main.tf
  examples/minimum/main.tf
  outputs.tf
Labels: enhancement
